# File: `docker-compose.yml`
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: gifty_app
        container_name: gifty_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
            - ./vendor:/var/www/html/vendor
            - ./node_modules:/var/www/html/node_modules
        depends_on:
            - db
        networks:
            - appnet

    web:
        image: nginx:1.25-alpine
        container_name: gifty_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - appnet

    db:
        image: mysql/mysql-server:8.0
        container_name: gifty_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret

        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - appnet

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - "8025:8025"
            - "1025:1025"
        container_name: gifty_mailpit
        restart: unless-stopped
        networks:
            - appnet
    redis:
        image: redis:alpine
        container_name: gifty_redis
        ports:
            - "6379:6379"
        networks:
            - appnet
volumes:
    dbdata:
        driver: local

networks:
    appnet:
        driver: bridge
